name: Build and Release

on:
  release:
    types: [published]

jobs:
  build_and_release:
    permissions: write-all
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        include:
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            ext: zip

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        target: ${{ matrix.target }}
        default: true

    - name: Build release
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release --target ${{ matrix.target }}

    - name: Package release
      run: |
        mkdir -p package
        cp target/${{ matrix.target }}/release/war3remap.exe package/
        cd package
        7z a ../war3remap-${{ matrix.target }}.${{ matrix.ext }} *
        cd ..

    - name: Upload release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./war3remap-${{ matrix.target }}.${{ matrix.ext }}
        asset_name: war3remap-${{ matrix.target }}.${{ matrix.ext }}
        asset_content_type: application/octet-stream